targets:
  $default:
    builders:
      source_gen|combining_builder:
        generate_for:
          - lib/**.dart
        options:
          build_extensions:
            {
              "lib/models/{{file}}.dart": "lib/models/generated/{{file}}.g.dart",
              "lib/providers/{{file}}.dart": "lib/providers/generated/{{file}}.g.dart",
            }
      freezed|freezed:
        options:
          build_extensions:
            "lib/models/{{file}}.dart": "lib/models/generated/{{file}}.freezed.dart"
      riverpod_generator:
        options:
          provider_name_prefix: ""
          provider_family_name_prefix: ""
          provider_name_suffix: "Provider"
          provider_family_name_suffix: "Provider"
      json_serializable:
        options:
          # Options configure how source code is generated for every
          # `@JsonSerializable`-annotated class in the package.
          #
          # The default value for each is listed.
          any_map: false
          checked: false
          constructor: ""
          create_factory: true
          create_field_map: false
          create_json_keys: false
          create_per_field_to_json: false
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: true
          field_rename: none
          generic_argument_factories: false
          ignore_unannotated: false
          include_if_null: true

